Localization
ecc521/mahjong pull request #97
Opened 2022-01-28 00:53 UTC by Miles-Mom

## Pull Request Details

Your text here

## Contributor Agreement
- [ x] I hold the rights to these contributions (if multiple rightsholders, please elaborate)
- x[ ] I understand that ecc521/mahjong is not an open-source project, and that the source code is not available under any open source license. 
- [x ] I grant ecc521 (Tucker Willenborg) a non-revokable transferrable perpetual worldwide license to sublicense, redistribute, modify, build upon, commercialize, reuse, and/or distribute these contributions. 
- [x ] This license is granted without any requirements or encumberments, absent attribution. I understand that no additional rights are granted to derivative works as a result of the integration of these contributions (ecc521/Tucker Willenborg will remain the sole rightsholder). 
- [ x] This license is granted with no requirements for attribution (optional for larger contributions - please elaborate if requesting attribution)

2022-01-28 01:02 UTC, ecc521 commented
Just FYI: I did receive your message, and am 100% good with attribution here, especially in the menu when Chinese is selected.

2022-01-28 01:12 UTC, ecc521 commented
Some of these files seem to have merged weirdly - GameBoard.js and RoomManager.js seem to be displaying changes based off an earlier version of the master branch, yet including the changes from the later branch. I'll need to take a close look, especially given the 7 merge conflicts in important files. 

I'll merge this into a test branch instead. It's a bit much to put into master yet.

2022-01-28 01:16 UTC, ecc521 commented
@Miles-Mom 
Is something wrong with the PR I'm not noticing?

2022-01-28 01:21 UTC, ecc521 commented
One other translation thing: 

I would be tempted to translate "English" to "English" (and vice-versa). It probably reduces the risk of users getting stuck in the wrong language.

2022-01-28 01:41 UTC, Miles-Mom commented
I just realized I was behind on git :( Will rework it in.

On Thu, Jan 27, 2022, 8:02 PM Tucker Willenborg ***@***.***>
wrote:

> Just FYI: I did receive your message, and am 100% good with attribution
> here, especially in the menu when Chinese is selected.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecc521/mahjong/pull/97#issuecomment-1023785981>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADXEKUH4U4OJD2J2XURTSX3UYHTLXANCNFSM5M7OG2NQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-01-28 01:45 UTC, Miles-Mom commented
Agree it is way too messy. Sorry about my clumsiness around Git..

I am thinking of get all your current master code in my local (checkout,
git pull, checkout, merge, as the instruction from GitHub), then put my
change in, then test, so on.

I probably have more time than you, but 5 times slower than you..

Thoughts?

On Thu, Jan 27, 2022, 8:41 PM Miles's Mom ***@***.***> wrote:

> I just realized I was behind on git :( Will rework it in.
>
> On Thu, Jan 27, 2022, 8:02 PM Tucker Willenborg ***@***.***>
> wrote:
>
>> Just FYI: I did receive your message, and am 100% good with attribution
>> here, especially in the menu when Chinese is selected.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ecc521/mahjong/pull/97#issuecomment-1023785981>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADXEKUH4U4OJD2J2XURTSX3UYHTLXANCNFSM5M7OG2NQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>> You are receiving this because you modified the open/close state.Message
>> ID: ***@***.***>
>>
>

2022-01-28 01:55 UTC, ecc521 commented
If you think you can pull off the update, that would help quite a bit. I'm happy to try and merge this as is, but I think breaking it up into two stages would make this much easier. 

I'll share a mostly-annotated copy of your email with you. It has a bit of info about the new settings stuff that should be used that might be helpful when pulling in the latest commits from master. 

I'm going to leave this PR open - It may update automatically, depending on how you pull in the changes from ecc521/master. Not going to accidentally merge it or anything.

2022-01-28 02:07 UTC, Miles-Mom commented
Ok it's the plan.

On Thu, Jan 27, 2022, 8:56 PM Tucker Willenborg ***@***.***>
wrote:

> If you think you can pull off the update, that would help quite a bit. I'm
> happy to try and merge this as is, but I think breaking it up into two
> stages would make this much easier.
>
> I'll share a mostly-annotated copy of your email with you. It has a bit of
> info about the new settings stuff that should be used that might be helpful
> when pulling in the latest commits from master.
>
> I'm going to leave this PR open - It may update automatically, depending
> on how you pull in the changes from ecc521/master, and helps me see where
> to look for potential issues. Not going to accidentally merge it or
> anything.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ecc521/mahjong/pull/97#issuecomment-1023811896>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADXEKUGETE4NSYNLJVY2U3TUYHZT5ANCNFSM5M7OG2NQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-29 03:54 UTC, ecc521 commented on packages/docs.js
> +/******/ (() => { // webpackBootstrap
Looks like the minimized build never finished for this. I'll remove the change.

2022-01-29 04:16 UTC, ecc521 requested changes
Looking quite close - comments attached. 

I'd try re-running the build and waiting a little bit (it builds non-minified code first, then does minified). That may well fix the 3 files that didn't have minified builds. 

I didn't actually do testing of the code, I merely read through it to confirm everything looked good. That'll come later when these are actually merged into master.

2022-01-29 04:16 UTC, ecc521 commented on webpackbuild.js
> +			"path": require.resolve('path-browserify'),
Did you do something here that requires the path-browserify module? Not sure I noticed where this would have changed?

2022-01-29 04:16 UTC, ecc521 commented on packagedsw.js
> -(()=>{var t={8222:(t,r,e)=>{e(1539),e(4916),e(3123);var n=["packages/index.js","packages/docs.js","packages/index.css","assets/edit.svg","assets/exit-full-screen.svg","assets/go-full-screen.svg","ass
It doesn't look like this file built properly (the minified build never finished in time?)

2022-01-29 04:16 UTC, ecc521 commented on packages/docs.js
> -(()=>{var t={7828:(t,r,e)=>{"use strict";e.d(r,{t:()=>q});
It doesn't look like this file built properly (the minified build never finished in time?)

2022-01-29 04:16 UTC, ecc521 commented on packages/universalLinks.js
> -(()=>{var t={9662:(t,e,r)=>{var n=r(7854),o=r(614),i=r(6330),a=n.TypeError;t.exports=function(t){if(o(t))return t;throw a(i(t)+" is not a function")}},6077:(t,e,r)=>{var n=r(7854),o=r(614),i=n.String
It doesn't look like this file built properly (the minified build never finished in time?)

2022-01-29 04:16 UTC, ecc521 commented on src/RoomManager.js
> +	connectionStatus.innerHTML = i18n.__("Multiplayer Needs Internet") + ".".repeat(1 + (++dots % 5))
I assume the "." ".." "..." "...." is interpreted as "loading" in Chinese and does not need any sort of translation?

2022-01-29 04:16 UTC, ecc521 commented on src/RoomManager.js
> +		link = "href=\"https://apps.apple.com/us/app/mahjong-4-friends/id1552704332\" target=\"_blank\""
It would probably be better to inline the href= and target= portion below on line 799 instead of here. As is, the target="blank" is included here, on line 792, and on line 796 so would need to be changed three times if it was ever changed. 

Also - consider using JavaScript template literals for this string to avoid the need to escape it (more readable in this instance):
So `target="blank"`

2022-01-29 04:16 UTC, ecc521 commented on src/RoomManager.js
> +copyrightNotice.innerHTML = i18n.__("Copyright © 2021, All Rights Reserved")
Might as well bump this up to 2022 while you're at it.

2022-01-29 04:27 UTC, ecc521 commented
Please ignore the stuff about packages/docs.js, packagedsw.js, universalLinks.js, and their .map files. 
If they aren't fixed, I will simply take those from the current master when merging, so it won't be an issue.

2022-01-29 04:27 UTC, ecc521 commented on packages/universalLinks.js
> -(()=>{var t={9662:(t,e,r)=>{var n=r(7854),o=r(614),i=r(6330),a=n.TypeError;t.exports=function(t){if(o(t))return t;throw a(i(t)+" is not a function")}},6077:(t,e,r)=>{var n=r(7854),o=r(614),i=n.String
See comment below (after this review). This is likely not a problem.

2022-01-29 04:27 UTC, ecc521 commented on packages/docs.js
> -(()=>{var t={7828:(t,r,e)=>{"use strict";e.d(r,{t:()=>q});
See comment below (after this review). This is likely not a problem.

2022-01-29 04:28 UTC, ecc521 commented on packagedsw.js
> -(()=>{var t={8222:(t,r,e)=>{e(1539),e(4916),e(3123);var n=["packages/index.js","packages/docs.js","packages/index.css","assets/edit.svg","assets/exit-full-screen.svg","assets/go-full-screen.svg","ass
See comment below (after this review). This is likely not a problem.

2022-01-29 04:52 UTC, Miles-Mom commented on src/RoomManager.js
> +	connectionStatus.innerHTML = i18n.__("Multiplayer Needs Internet") + ".".repeat(1 + (++dots % 5))
yes universal waiting :-)

2022-01-29 04:54 UTC, Miles-Mom commented
i'm just coming up for air after wrestling with Git... it seems this pull is automatically updated. Fingers crossed. will go through the reviews and catch up there.

2022-01-29 04:55 UTC, Miles-Mom commented on src/RoomManager.js
> +copyrightNotice.innerHTML = i18n.__("Copyright © 2021, All Rights Reserved")
got it.

2022-01-29 05:02 UTC, Miles-Mom commented on src/RoomManager.js
> +		link = "href=\"https://apps.apple.com/us/app/mahjong-4-friends/id1552704332\" target=\"_blank\""
Yes!!! Much better that way indeed.

2022-01-29 05:13 UTC, Miles-Mom commented on webpackbuild.js
> +			"path": require.resolve('path-browserify'),
The npm i18n library kept demanding that. I put that pacifier line in, and forgot about it. Guess what? After looking into i18n code more in detail, I think i have a work around to remove this requirement. Hooray!

Some day may be we'll just fix those weird bugs in i18n lib itself.

2022-01-29 05:15 UTC, Miles-Mom commented on packagedsw.js
> -(()=>{var t={8222:(t,r,e)=>{e(1539),e(4916),e(3123);var n=["packages/index.js","packages/docs.js","packages/index.css","assets/edit.svg","assets/exit-full-screen.svg","assets/go-full-screen.svg","ass
I probably copied some packaged stuff from the other branches trying to please the git.. I hope i got the right files in now.

2022-01-29 05:32 UTC, ecc521 requested changes
One of the minor changes I requested before looks like it's probably an actual bug.

Also: One of the three files built - other two still weird (but not worried about that)

2022-01-29 05:32 UTC, ecc521 commented on server/Room/goMahjong.js
> +	this.setAllInstructions([this.hostClientId], {format: ["%s went mahjong!", "\n", "Press End Game to return everybody to the room screen. "], args:client.getNickname()})
I think this is a bug. "You went Mahjong" should be based on clientId, not this.hostClientId (the host does not always win)
Just swap this.hostClientID for clientId on this line and line 61

2022-01-29 05:32 UTC, ecc521 commented on src/RoomManager.js
> +		link = `href="https://apps.apple.com/us/app/mahjong-4-friends/id1552704332"`
The href= portion should be moved out of here too.

2022-01-29 05:32 UTC, ecc521 commented on src/RoomManager.js
> +	link +=  ` target="_blank"`
This looks like a bug - isn't link being inserted twice, both into the <a> tag's property, and into its innerHTML? This would result in the target="_blank" being part of the link, which isn't correct. 

This may need some more complex logic on line 800. Possibly insert the HTML code into line 800 directly?

2022-01-29 05:34 UTC, ecc521 commented on server/Room/goMahjong.js
> +	this.setAllInstructions([this.hostClientId], {format: ["%s went mahjong!", "\n", "Press End Game to return everybody to the room screen. "], args:client.getNickname()})
Current master branch has 
```

	this.setAllInstructions([clientId], client.getNickname() + " went mahjong!\nPress End Game to return everybody to the room screen. ")
	this.setInstructions(clientId, "You went mahjong!\nPress End Game to return everybody to the room screen. ")

```

2022-01-29 05:39 UTC, ecc521 commented on src/settingsMenu.js
> +	popup.ondismissed = refreshScreen
Nice move. I probably wouldn't have though about waiting for popup closure.

2022-01-29 05:41 UTC, Miles-Mom commented on server/Room/goMahjong.js
> +	this.setAllInstructions([this.hostClientId], {format: ["%s went mahjong!", "\n", "Press End Game to return everybody to the room screen. "], args:client.getNickname()})
Nice catch!

2022-01-29 05:43 UTC, ecc521 commented
@Miles-Mom 
I suspect we're doing things simultaniously? I believe the latest review (12:35 AM EST or so) should be up to date as of now

2022-01-29 05:54 UTC, Miles-Mom commented on src/RoomManager.js
> +		link = `href="https://apps.apple.com/us/app/mahjong-4-friends/id1552704332"`
agreed.

2022-01-29 05:57 UTC, Miles-Mom commented on src/RoomManager.js
> +	link +=  ` target="_blank"`
the link var is the link anchor part, <a %s-this-is-our-link-blank-target-included>%s-this-is-the-prompt</a>. I think it works fine. I did the if (1 ||...) testing and they look okay. I didn't want the details to go into the actual string to be translated, thinking mistakes likely to happen and they are not as easy to test also.

2022-01-29 05:58 UTC, Miles-Mom commented on src/settingsMenu.js
> +	popup.ondismissed = refreshScreen
Thanks!

2022-01-29 06:08 UTC, Miles-Mom commented
I am beat... done here also. Noticed one new feature : No Automatic Sorting default to No, and the double negative got me twisted in translation for quite a while. Why not Automatic Sorting and default to Yes? nitpicking i am here.

Later tomorrow.

2022-01-29 15:50 UTC, ecc521 approved these changes

2022-01-29 15:50 UTC, ecc521 commented on src/RoomManager.js
>  	ratingPrompt.innerHTML = i18n.__("Enjoying Mahjong 4 Friends? Please <a %s>%s</a>", link, i18n.__(prompt) )
I think line 800 is still bugged, but I'll sort it out if it is.

2022-01-29 15:51 UTC, merged

2022-01-29 16:00 UTC, ecc521 commented
Correction - line 800 is correct. I was confused.